server/config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :fileobjects
  devise_for :users

  resources :projects
  resources :consolidations
  
  root 'projects#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

server/app/models/consolidation.rb
class Consolidation < ApplicationRecord
end

server/app/controllers/consolidations_controller.rb
class ConsolidationsController < ApplicationController
  before_action :set_consolidation, only: [:show, :edit, :update, :destroy]
  
  PER = 10
  
  # GET /consolidations
  # GET /consolidations.json
  def index
    @consolidations = Consolidation.all.order(created_at: 'desc')
  end

  # GET /consolidations/1
  # GET /consolidations/1.json
  def show
    @fileobjects = Fileobject.where(consolidation: @consolidation.uuid, material:"").page(params[:page]).per(PER)
    @materials = Material.where(consolidation: @consolidation.uuid).page(params[:page]).per(PER)
  end

  # GET /consolidations/new
  def new
    @consolidation = Consolidation.new
    @consolidation.uuid = SecureRandom.uuid
    @consolidation.project = params[:project]
  end

  # GET /consolidations/1/edit
  def edit
  end

  # POST /consolidations
  # POST /consolidations.json
  def create
    @consolidation = Consolidation.new(consolidation_params)

    respond_to do |format|
      if @consolidation.save
        prj_uuid = @consolidation.project
        project = Project.where(uuid: prj_uuid).first
        
        format.html { redirect_to project_url(project), notice: 'Consolidation was successfully created.'}
        format.json { render :show, status: :created, location: @consolidation }
      else
        format.html { render :new }
        format.json { render json: @consolidation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consolidations/1
  # PATCH/PUT /consolidations/1.json
  def update
    respond_to do |format|
      if @consolidation.update(consolidation_params)
        logger.debug(params)
        format.html {
          redirect_to consolidation_url(
                                          :id => @consolidation.id,
                                          params: {
                                            :lid => params[:consolidation][:pid]
                                          }
                                       ),
          notice: 'Consolidation was successfully updated.'}
        format.json { render :show, status: :ok, location: @consolidation }
      else
        format.html { render :edit }
        format.json { render json: @consolidation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consolidations/1
  # DELETE /consolidations/1.json
  def destroy
    materials = Material.where(consolidation: @consolidation.uuid)
    materials.each do |material|
      material.destroy
    end
    
    fileobjects = Fileobject.where(consolidation: @consolidation.uuid)
    fileobjects.each do |fileobject|
      fileobject.destroy
    end
    
    @consolidation.destroy
    respond_to do |format|
      prj_uuid = @consolidation.project
      project = Project.where(uuid: prj_uuid).first
      
      format.html { redirect_to project_url(project), notice: 'Consolidation was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consolidation
      @consolidation = Consolidation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consolidation_params
      params.require(:consolidation).permit(:uuid, :name, :geographic_annotation, :temporal_annotation, :description, :flickr_photosetid, :project)
    end
end

server/app/helpers/consolidations_helper.rb
module ConsolidationsHelper
end

server/app/views/consolidations/_form.html.erb
<%= form_with(model: consolidation, local: true) do |form| %>
  <% if consolidation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consolidation.errors.count, "error") %> prohibited this consolidation from being saved:</h2>

      <ul>
      <% consolidation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-sm-12">
      <table>
        <tr>
          <th style="width: 150px"><%= form.label :uuid %></th>
          <td  style="width: 300px"><%= form.text_field :uuid, :class => "text_field", :readonly => true %></td></tr>
        <tr><th><%= form.label :project %></th><td style="width: 300px"><%= form.text_field :project, :class => "text_field", :readonly => true  %></td></tr>
        <tr><th><%= form.label :name %></th><td style="width: 300px"><%= form.text_field :name, :class => "text_field" %></td></tr>
        <tr><th><%= form.label :geographic_annotation %></th><td style="width: 300px"><%= form.text_field :geographic_annotation, :class => "text_field" %></td></tr>
        <tr><th><%= form.label :temporal_annotation %></th><td style="width: 300px"><%= form.text_field :temporal_annotation, :class => "text_field" %></td></tr>
        <tr><th><%= form.label :description %></th><td style="width: 300px"><%= form.text_area :description, :class => "text_field" %></td></tr>
        <tr><th><%= form.label :flickr_photosetid %></th><td style="width: 300px"><%= form.text_field :flickr_photosetid, :class => "text_field" %></td></tr>
      </table>
    
      <div class="actions" style="text-align: right">
          <%= form.hidden_field :pid, :value => params[:lid], :id => "pid", :post => true %>
          <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>
  

server/app/views/consolidations/edit.html.erb
<h2>
 <img src=<%= image_url('icons/ic_inbox_black_48dp.png') %> />
 Editing Consolidation
</h2>

<div class="btn-group">
 <%= button_to consolidation_url(@consolidation),
  {method: :get, :class => "btn btn-secondary",
   :style => "width: 90px; border-radius: 0 !important;",
   params: {uuid: params[:project], lid: params[:lid]}} do%>
   <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
 <% end %>
</div>
<hr />

<%= render 'form', consolidation: @consolidation %>

server/app/views/consolidations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consolidations</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Name</th>
      <th>Geographic annotation</th>
      <th>Temporal annotation</th>
      <th>Description</th>
      <th>Flickr photosetid</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consolidations.each do |consolidation| %>
      <tr>
        <td><%= consolidation.uuid %></td>
        <td><%= consolidation.name %></td>
        <td><%= consolidation.geographic_annotation %></td>
        <td><%= consolidation.temporal_annotation %></td>
        <td><%= consolidation.description %></td>
        <td><%= consolidation.flickr_photosetid %></td>
        <td><%= consolidation.project %></td>
        <td><%= link_to 'Show', consolidation %></td>
        <td><%= link_to 'Edit', edit_consolidation_path(consolidation) %></td>
        <td><%= link_to 'Destroy', consolidation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consolidation', new_consolidation_path %>

server/app/views/consolidations/new.html.erb
<h2>New Consolidation</h2>
<hr />
<div class="btn-group">
  <%= button_to 'Back', project_url(:id => params[:lid]), {method: :get, :class => "btn btn-secondary", :style => "width: 90px; border-radius: 0 !important;"} %>
</div>
<hr />

<%= render 'form', consolidation: @consolidation %>

server/app/views/consolidations/show.html.erb
<h2>
 <img src=<%= image_url('icons/ic_inbox_black_48dp.png') %> />
 Consolidation: <%= @consolidation.name %>
</h2>
<hr />
<div class="btn-group">
 <%= button_to project_url(:id => params[:lid]),
  {method: :get, :class => "btn btn-secondary",
   :style => "width: 90px; border-radius: 0 !important;"} do%>
  <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
 <% end %>
 <%= button_to edit_consolidation_path(@consolidation),
  {method: :get, :class => "btn btn-warning",
   :style => "width: 90px; border-radius: 0 !important;",
   params: {uuid: params[:project], lid: params[:lid]}} do%>
   <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
 <% end %>
</div>
<hr />

<div class="row">
  <div class="col-sm-12">
    <p><strong>Uuid:</strong><%= @consolidation.uuid %></p>
    <p><strong>Geographic annotation:</strong><%= @consolidation.geographic_annotation %></p>
    <p><strong>Temporal annotation:</strong><%= @consolidation.temporal_annotation %></p>
    <p><strong>Description:</strong><%= @consolidation.description %></p>
    <p><strong>Flickr photosetid:</strong><%= @consolidation.flickr_photosetid %></p>
    <p><strong>Project:</strong><%= @consolidation.project %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
   <hr />
   <h3>
     <img src=<%= image_url('icons/ic_my_library_books_black_36dp.png') %> />Files
   </h3>
   <hr />
   <%=
    button_to 'New File',
    new_fileobject_path,
    {
     method: :get,
     :class => "btn btn-success",
     :style => "width: 150px; border-radius: 0 !important;",
     params: {
      type: "consolidation",
      consolidation: @consolidation.uuid,
      cid: @consolidation.id,
      pid: params[:lid]
      }
     }
    %>
   <hr />
   
   <div><%= paginate @fileobjects %></div>
   
   <table>
     <thead>
       <tr>
         <th style="width: 100px">Modified</th>
         <th style="width: 300px">Name</th>
         <th style="width: 300px">Alias</th>
         <th style="width: 100px">Type</th>
         <th style="width: 100px">Status</th>
         <th style="width: 100px">Public</th>
         <th style="width: auto"></th>
       </tr>
     </thead>
     
     <tbody>
       <% @fileobjects.each do |fileobject| %>
         <tr class="zebra">
           <td><%= fileobject.modified_date %></td>
           <td><%= fileobject.file %></td>
           <td><%= fileobject.alias_name %></td>
           <td style="text-align: center"><%= fileobject.file_type %></td>
           <td style="text-align: center"><%= fileobject.status %></td>
           <td style="text-align: center"><%= fileobject.make_public %></td>
           <td>
             <div class="btn-group">
             <%= button_to fileobject,
              {method: :get, :class => "btn btn-primary",
               :style => "width: 50px; border-radius: 0 !important;",
               params: {type: "consolidation", cid: @consolidation.id, pid: params[:lid]}} do %>
               <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
              <% end %>
             <%= button_to edit_fileobject_path(fileobject),
              {method: :get, :class => "btn btn-warning",
               :style => "width: 50px; border-radius: 0 !important;",
               params: {type: "consolidation", cid: @consolidation.id, pid: params[:lid]}} do %>
               <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
              <% end %>
             <%= button_to fileobject,
              method: :delete, data: { confirm: 'Are you sure?' },
              :class => "btn btn-danger",
              :style => "width: 50px; border-radius: 0 !important;",
              params: {type: "consolidation", cid: @consolidation.id, pid: params[:lid]} do %>
              <img src=<%= image_url('icons/ic_delete_white_18dp.png') %>/>
             <% end %>
            </div>
           </td>
         </tr>
       <% end %>
     </tbody>
   </table>
  </div>
</div>


<div class="row">
  <div class="col-sm-12">
   <hr />
   <h3>
     <img src=<%= image_url('icons/ic_filter_none_black_36dp.png') %> />Materials
   </h3>
   <hr />
   <%=
    button_to 'New Material',
    new_material_path,
    {
     method: :get,
     :class => "btn btn-success",
     :style => "width: 150px; border-radius: 0 !important;",
     params: {
      consolidation: @consolidation.uuid,
      cid: @consolidation.id,
      pid: params[:lid]
      }
     }
    %>
   <hr />
   
   <div><%= paginate @materials %></div>
   
   <table>
     <thead>
       <tr>
         <th style="width: 200px">Name</th>
         <th style="width: 200px">Material number</th>
         <th style="width: 100px">Beginning</th>
         <th style="width: 100px">Peak</th>
         <th style="width: 100px">Ending</th>
         <th style="width: 100px">Latitude</th>
         <th style="width: 100px">Longitude</th>
         <th style="width: 100px">Altitude</th>
       </tr>
     </thead>
     
     <tbody>
       <% @materials.each do |material| %>
         <tr class="zebra">
           <td><%= material.name %></td>
           <td style="text-align: center"><%= material.material_number %></td>
           <td style="text-align: center"><%= material.estimated_period_beginning %></td>
           <td style="text-align: center"><%= material.estimated_period_peak %></td>
           <td style="text-align: center"><%= material.estimated_period_ending %></td>
           <td style="text-align: center"><%= material.latitude %></td>
           <td style="text-align: center"><%= material.longitude %></td>
           <td style="text-align: center"><%= material.altitude %></td>
           <td>
             <div class="btn-group">
             <%= button_to material,
              {method: :get, :class => "btn btn-primary",
               :style => "width: 50px; border-radius: 0 !important;",
               params: {cid: @consolidation.id, pid: params[:lid]}} do %>
               <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
              <% end %>
             <%= button_to edit_material_path(material),
              {method: :get, :class => "btn btn-warning",
               :style => "width: 50px; border-radius: 0 !important;",
               params: {cid: @consolidation.id, pid: params[:lid]}} do %>
               <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
              <% end %>
             <%= button_to material,
              method: :delete, data: { confirm: 'Are you sure?' },
              :class => "btn btn-danger",
              :style => "width: 50px; border-radius: 0 !important;",
              params: {cid: @consolidation.id, pid: params[:lid]} do %>
              <img src=<%= image_url('icons/ic_delete_white_18dp.png') %>/>
             <% end %>
            </div>
           </td>
         </tr>
       <% end %>
     </tbody>
   </table>
  </div>
</div>