server/config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :fileobjects
  devise_for :users

  resources :projects
  resources :consolidations
  
  root 'projects#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

server/app/models/material.rb
class Material < ApplicationRecord
end

server/app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  
  PER = 10
  
  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    @fileobjects = Fileobject.where(material: @material.uuid).page(params[:page]).per(PER)
  end

  # GET /materials/new
  def new
    @material = Material.new
    @material.uuid = SecureRandom.uuid
    @material.consolidation = params[:consolidation]
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)
    
    respond_to do |format|
      if @material.save
        format.html {
          redirect_to consolidation_url(
                                            :id => params[:material][:cid],
                                            params: {
                                              :lid => params[:material][:pid]
                                            }
                                          ),
              notice: 'File was successfully created.'}
          
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        
        
        format.html {
          redirect_to material_url(
                                   :id => @material.id,
                                   params: {
                                     :cid => params[:material][:cid],
                                     :pid => params[:material][:pid]
                                   }),
          notice: 'Material was successfully updated.'
        }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    # Delete files related to the material.
    fileobjects = Fileobject.where(material: @material.uuid)
    fileobjects.each do |fileobject|
      fileobject.destroy
    end
    
    # Delete the material.
    @material.destroy
    respond_to do |format|
      format.html { redirect_to consolidation_url(:id => params[:cid], params: {:lid => params[:pid]}),
          notice: 'Fileobject was successfully destroyed.'
        }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(
                                       :uuid,
                                       :consolidation,
                                       :name,
                                       :material_number,
                                       :estimated_period_beginning,
                                       :estimated_period_peak,
                                       :estimated_period_ending,
                                       :latitude,
                                       :longitude,
                                       :altitude,
                                       :description)
    end
end

server/app/helpers/materials_helper.rb
module MaterialsHelper
end

server/app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-sm-12">
      <table>
          <tr>
            <th style="width: 150px"><%= form.label :uuid %></th>
            <td  style="width: 300px"><%= form.text_field :uuid, :class => "text_field", :readonly => true %></td></tr>
          <tr><th><%= form.label :consolidation %></th><td style="width: 300px"><%= form.text_field :consolidation, :class => "text_field", :readonly => true  %></td></tr>
          <tr><th><%= form.label :name %></th><td style="width: 300px"><%= form.text_field :name, :class => "text_field" %></td></tr>
          <tr><th><%= form.label :material_number %></th><td style="width: 300px"><%= form.text_field :material_number, :class => "text_field" %></td></tr>
          <tr><th><%= form.label :estimated_period_beginning %></th><td style="width: 300px"><%= form.date_field :estimated_period_beginning, :class => "text_field" %></td></tr>
          <tr><th><%= form.label :estimated_period_peak %></th><td style="width: 300px"><%= form.date_field :estimated_period_peak, :class => "text_field" %></td></tr>
          <tr><th><%= form.label :estimated_period_ending %></th><td style="width: 300px"><%= form.date_field :estimated_period_ending, :class => "text_field" %></td></tr>
          <tr><th><%= form.label :latitude %></th><td style="width: 300px"><%= form.number_field :latitude, :class => "text_field", :step => "0.0000001" %></td></tr>
          <tr><th><%= form.label :longitude %></th><td style="width: 300px"><%= form.number_field :longitude, :class => "text_field", :step => "0.0000001" %></td></tr>
          <tr><th><%= form.label :altitude %></th><td style="width: 300px"><%= form.number_field :altitude, :class => "text_field", :step => "0.0000001" %></td></tr>
          <tr><th><%= form.label :description %></th><td style="width: 300px"><%= form.text_area :description, :class => "text_field" %></td></tr>
        </table>
        <div class="actions" style="text-align: right">
          <%= form.hidden_field :cid, :value => params[:cid], :id => "cid", :post => true %>
          <%= form.hidden_field :pid, :value => params[:pid], :id => "pid", :post => true %>
          <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

server/app/views/materials/edit.html.erb
<h2>
    <img src=<%= image_url('icons/ic_inbox_black_48dp.png') %> />
    Editing Material: <%= @material.uuid %>
</h2>

<div class="btn-group">
 <%= button_to material_url(@material),
  {method: :get, :class => "btn btn-secondary",
   :style => "width: 90px; border-radius: 0 !important;",
   params: {cid: params[:cid], pid: params[:pid]}
  } do%>
   <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
 <% end %>
</div>
<hr />

<%= render 'form', material: @material %>

server/app/views/materials/index.html.erb
<h1>Materials</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Consolidation</th>
      <th>Name</th>
      <th>Material number</th>
      <th>Estimated period beginning</th>
      <th>Estimated period peak</th>
      <th>Estimated period ending</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Altitude</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.uuid %></td>
        <td><%= material.consolidation %></td>
        <td><%= material.name %></td>
        <td><%= material.material_number %></td>
        <td><%= material.estimated_period_beginning %></td>
        <td><%= material.estimated_period_peak %></td>
        <td><%= material.estimated_period_ending %></td>
        <td><%= material.latitude %></td>
        <td><%= material.longitude %></td>
        <td><%= material.altitude %></td>
        <td><%= material.description %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

server/app/views/materials/new.html.erb
<h2>
  <img src=<%= image_url('icons/ic_filter_none_black_48dp.png') %> />
  New Material
</h2>
<hr />
<div class="btn-group">
  <%=
    button_to consolidation_url(:id => params[:cid]),
    {
      method: :get, :class => "btn btn-secondary",
      :style => "width: 90px; border-radius: 0 !important;",
      params: {:lid => params[:pid]}
    } do %>
        <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
  <% end %>
</div>
<hr />

<%= render 'form', material: @material %>

server/app/views/materials/show.html.erb
<h2>
 <img src=<%= image_url('icons/ic_filter_none_black_48dp.png') %> />
 Material: <%= @material.uuid %>
</h2>
<hr />
<div class="btn-group">
    <%=
     button_to consolidation_url(:id => params[:cid]),
     {
      method: :get, :class => "btn btn-secondary",
      :style => "width: 90px; border-radius: 0 !important;",
      params: {:lid => params[:pid]}
     } do %>
     <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
    <% end %>
    <%=
     button_to edit_material_path(@material),
     {
      method: :get, :class => "btn btn-warning",
      :style => "width: 90px; border-radius: 0 !important;",
      params: {type: params[:type], cid: params[:cid], pid: params[:pid]}
     } do %>
     <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
    <% end %>
</div>
<hr />

<div class="row">
  <div class="col-sm-12">
    <p><strong>Consolidation:</strong><%= @material.consolidation %></p>
    <p><strong>Name:</strong><%= @material.name %></p>
    <p><strong>Material number:</strong><%= @material.material_number %></p>
    <p><strong>Estimated period beginning:</strong><%= @material.estimated_period_beginning %></p>
    <p><strong>Estimated period peak:</strong><%= @material.estimated_period_peak %></p>
    <p><strong>Estimated period ending:</strong><%= @material.estimated_period_ending %></p>
    <p><strong>Latitude:</strong><%= @material.latitude %></p>
    <p><strong>Longitude:</strong><%= @material.longitude %></p>
    <p><strong>Altitude:</strong><%= @material.altitude %></p>
    <p><strong>Description:</strong><%= @material.description %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
   <hr />
   <h3>
     <img src=<%= image_url('icons/ic_my_library_books_black_36dp.png') %> />Files
   </h3>
   <hr />
   <%=
    button_to 'New File',
    new_fileobject_path,
    {
     method: :get,
     :class => "btn btn-success",
     :style => "width: 150px; border-radius: 0 !important;",
     params: {
      type: "material",
      consolidation: @material.consolidation,
      material: @material.uuid,
      mid: @material.id,
      cid: params[:cid],
      pid: params[:pid]
      }
     }
    %>
   <hr />
   
   <div><%= paginate @fileobjects %></div>
   
   <table>
     <thead>
       <tr>
         <th style="width: 100px">Modified</th>
         <th style="width: 300px">Name</th>
         <th style="width: 300px">Alias</th>
         <th style="width: 100px">Type</th>
         <th style="width: 100px">Status</th>
         <th style="width: 100px">Public</th>
         <th style="width: auto"></th>
       </tr>
     </thead>
     
     <tbody>
       <% @fileobjects.each do |fileobject| %>
         <tr class="zebra">
           <td><%= fileobject.modified_date %></td>
           <td><%= fileobject.file %></td>
           <td><%= fileobject.alias_name %></td>
           <td style="text-align: center"td><%= fileobject.file_type %></td style="text-align: center"td>
           <td style="text-align: center"td><%= fileobject.status %></td style="text-align: center"td>
           <td style="text-align: center"><%= fileobject.make_public %></td>
           <td>
             <div class="btn-group">
             <%= button_to fileobject,
              {method: :get, :class => "btn btn-primary",
               :style => "width: 50px; border-radius: 0 !important;",
               params: {type: "material", mid: @material.id, cid: params[:cid], pid: params[:pid]}} do %>
               <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
              <% end %>
             <%= button_to edit_fileobject_path(fileobject),
              {method: :get, :class => "btn btn-warning",
               :style => "width: 50px; border-radius: 0 !important;",
               params: {type: "material", mid: @material.id, cid: params[:cid], pid: params[:pid]}} do %>
               <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
              <% end %>
             <%= button_to fileobject,
              method: :delete, data: { confirm: 'Are you sure?' },
              :class => "btn btn-danger",
              :style => "width: 50px; border-radius: 0 !important;",
              params: {type: "material", mid: @material.id, cid: params[:cid], pid: params[:pid]} do %>
              <img src=<%= image_url('icons/ic_delete_white_18dp.png') %>/>
             <% end %>
            </div>
           </td>
         </tr>
       <% end %>
     </tbody>
   </table>
  </div>
</div>