server/config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :fileobjects
  devise_for :users

  resources :projects
  resources :consolidations
  
  root 'projects#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

server/app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :cover, CoverUploader
end

server/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  PER = 10
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.page(params[:page]).per(PER)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @consolidations = Consolidation.where(project: @project.uuid).page(params[:page]).per(PER)
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.uuid = SecureRandom.uuid
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    consolidations = Consolidation.where(project: @project.uuid)
    consolidations.each do |consolidation|
      consolidation.destroy
    end
    
    @project.destroy
    
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:uuid, :name, :title, :begining, :ending, :phase, :introduction, :cause, :created_by, :cover, :cover_cache)
    end
end

server/app/helpers/projects_helper.rb
module ProjectsHelper
end

server/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
    <tr>
      <td colspan="2">
        <div class="field" style="text-align: center">
          <% if @project.cover.url %>
            <%= image_tag(@project.cover.url, :height => "300px") %> <br />
            <%= form.file_field :cover %>
            <%= form.hidden_field :cover_cache %>
          <% else %>
            <img src=<%= image_url('noimage.jpg') %> height="300px" width="550px" /> <br />
            <%= form.file_field :cover %>
            <%= form.hidden_field :cover_cache %>
          <% end %>
        </div>
      </td>
    </tr>
    <tr>
      <th style="width: 150px"><%= form.label :uuid %></th>
      <td style="width: 300px"><%= form.text_field :uuid, :class => "text_field", :readonly => true %></td>
    </tr>
    <tr><th><%= form.label :name %></th><td style="width: 300px"><%= form.text_field :name, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :title %></th><td style="width: 300px"><%= form.text_field :title, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :begining %></th><td style="width: 300px"><%= form.date_select :begining %></td></tr>
    <tr><th><%= form.label :ending %></th><td style="width: 300px"><%= form.date_select :ending %></td></tr>
    <tr><th><%= form.label :phase %></th><td style="width: 300px"><%= form.number_field :phase %></td></tr>
    <tr><th><%= form.label :introduction %></th><td style="width: 300px"><%= form.text_area :introduction, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :cause %></th><td style="width: 300px"><%= form.text_area :cause, :class => "text_field" %></td></tr>
    <tr>
      <th><%= form.label :created_by %></th><td style="width: 300px"><%= form.text_field :created_by, :class => "text_field",:value => current_user.username %></td></tr>
  </table>


  <div class="actions" style="text-align: right">
    <%= form.submit %>
  </div>
<% end %>

server/app/views/projects/edit.html.erb
<h2>
  <img src=<%= image_url('icons/ic_language_black_48dp.png') %> />
  Editing Project</h2>
<hr />
<div class="btn-group">
 <%= button_to projects_path,
  {method: :get, :class => "btn btn-secondary",
   :style => "width: 90px; border-radius: 0 !important;"} do %>
  <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
 <% end %>
 <%= button_to @project,
  {method: :get, :class => "btn btn-primary",
   :style => "width: 90px; border-radius: 0 !important;",
   params: {uuid: params[:project], lid: params[:lid]}} do%>
   <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
 <% end %>
</div>

<hr />

<%= render 'form', project: @project %>

server/app/views/projects/index.html.erb
<h2>
 <img src=<%= image_url('icons/ic_language_black_48dp.png') %> />
 Projects
</h2>
<hr />
  <div class="btn-group">
   <%= button_to new_project_path,
    {method: :get, :class => "btn btn-success",
      :style => "width: 150px; border-radius: 0 !important;"} do%>
    <img src=<%= image_url('icons/ic_add_circle_outline_white_18dp.png') %>/> New Project
   <% end %>
  </div>
<hr />

<div><%= paginate @projects %></div>

<table>
  <thead>
    <tr>
      <th style="width: 100px"></th>
      <th style="width: 300px">Name</th>
      <th style="width: 300px">Title</th>
      <th style="width: 100px">Begining</th>
      <th style="width: 100px">Ending</th>
      <th style="width: 100px">Phase</th>
      <th style="width: auto"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr class="zebra">
        <td>
          <% if project.cover.url != nil %>
            <%= image_tag(project.cover.url, :width => "99px", :height => "66px") %>
          <% else %>
            <img src=<%= image_url('noimage.jpg') %> width="99px" height="66px" />
           <% end %>
        </td>
        <td><%= project.name %></td>
        <td><%= project.title %></td>
        <td><%= project.begining %></td>
        <td><%= project.ending %></td>
        <td><%= project.phase %></td>
        <td>
          <div class="btn-group">
          <%= button_to project,
           {method: :get, :class => "btn btn-primary",
            :style => "width: 50px; border-radius: 0 !important;"} do %>
            <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
           <% end %>
          <%= button_to edit_project_path(project),
           {method: :get, :class => "btn btn-warning",
            :style => "width: 50px; border-radius: 0 !important;"} do %>
            <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
           <% end %>
          <%= button_to project,
           method: :delete, data: { confirm: 'Are you sure?' },
           :class => "btn btn-danger",
           :style => "width: 50px; border-radius: 0 !important;" do %>
           <img src=<%= image_url('icons/ic_delete_white_18dp.png') %>/>
          <% end %>
         </div>
        </td>
      </tr>
    <% end %>
    
  </tbody>
</table>
<hr />

server/app/views/projects/new.html.erb
<h2>
 <img src=<%= image_url('icons/ic_account_balance_black_48dp.png') %> />
 New Project
</h2>
<hr />
<%=
  button_to 'Back',
  projects_path,
  {
    method: :get,
    :class => "btn btn-secondary",
    :style => "width: 90px; border-radius: 0 !important;"
  }
%>
<hr />

<%= render 'form', project: @project %>

server/app/views/projects/show.html.erb
<h2>
 <img src=<%= image_url('icons/ic_account_balance_black_48dp.png') %> />
 Project: <%= @project.name %>
</h2>
<hr />
<div class="btn-group">
 <%= button_to projects_path,
  {method: :get, :class => "btn btn-secondary",
   :style => "width: 90px; border-radius: 0 !important;"} do %>
  <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
 <% end %>
 <%= button_to edit_project_path(@project),
  {method: :get, :class => "btn btn-warning",
   :style => "width: 90px; border-radius: 0 !important;",
   params: {uuid: params[:project], lid: params[:lid]}} do%>
   <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
 <% end %>
</div>
<hr />

<div class="row">
  <div class="col-sm-6" style="text-align: center; vertical-align: middle">
    <% if @project.cover.url != nil %>
     <%
         img_width, img_height = FastImage.size(@project.cover.path)
         if img_width >= img_height
             shw_height = (img_height * 550) / img_width
             shw_width = 550
         else
             shw_width = (img_width * 400) / img_height
             shw_height = 400
         end
     %>
     <%= image_tag(@project.cover.url, :height => shw_height, :width => shw_width) %>
    <% else %>
     <img src=<%= image_url('noimage.jpg') %> width="550px" />
    <% end %>
  </div>
  
  <div class="col-sm-6">
    <p><strong>Uuid:</strong><%= @project.uuid %></p>
    <p><strong>Title:</strong><%= @project.title %></p>
    <p><strong>Begining:</strong><%= @project.begining %></p>
    <p><strong>Ending:</strong><%= @project.ending %></p>
    <p><strong>Phase:</strong><%= @project.phase %></p>
    <p><strong>Introduction:</strong><%= @project.introduction %></p>
    <p><strong>Cause:</strong><%= @project.cause %></p>
    <p><strong>Created by:</strong><%= @project.created_by %></p>
  </div>
</div>


<hr />
<h3>
 <img src=<%= image_url('icons/ic_inbox_black_36dp.png') %> />
 Consolidations
</h3>
<hr />
<div class="btn-group">
 <%= button_to new_consolidation_path,
  {method: :get, :class => "btn btn-success",
  :style => "width: 200px; border-radius: 0 !important;",
  params: {project: @project.uuid, lid:@project.id}} do%>
  <img src=<%= image_url('icons/ic_add_circle_outline_white_18dp.png') %>/> New Consolidation
 <% end %>
</div>
<hr />


<div><%= paginate @consolidations %></div>

<table>
  <thead>
    <tr>
      <th style="width: 250px">Name</th>
      <th style="width: 200px">Geography</th>
      <th style="width: 200px">Temporal Info</th>
      <th style="width: 350px">Description</th>
      <th style="width: auto"></th>
    </tr>
  </thead>

 <tbody>
    <% @consolidations.each do |consolidation| %>
      <tr class="zebra">
        <td><%= consolidation.name %></td>
        <td><%= consolidation.geographic_annotation %></td>
        <td><%= consolidation.temporal_annotation %></td>
        <td><%= consolidation.description %></td>
        <td>
         <div class="btn-group">
          <%= button_to consolidation,
           {method: :get, :class => "btn btn-primary",
            :style => "width: 50px; border-radius: 0 !important;",
            params: {project: @project.uuid, lid:@project.id}} do %>
            <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
           <% end %>
          <%= button_to edit_consolidation_path(consolidation),
           {method: :get, :class => "btn btn-warning",
            :style => "width: 50px; border-radius: 0 !important;",
            params: {project: @project.uuid, lid:@project.id}} do %>
            <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
           <% end %>
          <%= button_to consolidation,
           method: :delete, data: { confirm: 'Are you sure?' },
           :class => "btn btn-danger",
           :style => "width: 50px; border-radius: 0 !important;" do %>
           <img src=<%= image_url('icons/ic_delete_white_18dp.png') %>/>
          <% end %>
         </div>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>