server/config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :fileobjects
  devise_for :users

  resources :projects
  resources :consolidations
  
  root 'projects#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

server/app/models/fileobject.rb
class Fileobject < ApplicationRecord
  mount_uploader :file, FileUploader
  validates :file, presence: true
end

server/app/controllers/fileobjects_controller.rb
class FileobjectsController < ApplicationController
  before_action :set_fileobject, only: [:show, :edit, :update, :destroy]

  # GET /fileobjects
  # GET /fileobjects.json
  def index
    @fileobjects = Fileobject.all
  end

  # GET /fileobjects/1
  # GET /fileobjects/1.json
  def show
  end

  # GET /fileobjects/new
  def new
    @fileobject = Fileobject.new
    @fileobject.uuid = SecureRandom.uuid
    @fileobject.status = "uploaded"
    @fileobject.operating_application = "Survey Project Manager II"
    @fileobject.file_operation = "Uploading"
    @fileobject.description = "This file is uploaded by Survey Project Manager II"
    
    if params[:type] == "consolidation"
      @fileobject.consolidation = params[:consolidation]
    elsif params[:type] == "material"
      @fileobject.consolidation = params[:consolidation]
      @fileobject.material = params[:material]
    end
    
  end

  # GET /fileobjects/1/edit
  def edit
    
  end

  # POST /fileobjects
  # POST /fileobjects.json
  def create
    @fileobject = Fileobject.new(fileobject_params)
    
    # Get the file uploaded file url.
    file = @fileobject.file.url
    
    if file != nil
      extension = @fileobject.file.file.extension.downcase
      
      if %w{jpg png gif bmp jpeg tif tiff}.include?(extension)
        @fileobject.file_type = "Image"
      elsif %w{wav wave mp3}.include?(extension)
        @fileobject.file_type = "Sound"
      end
      
      respond_to do |format|
        if @fileobject.save
          if params[:fileobject][:type] == "consolidation"
            format.html {
              redirect_to consolidation_url(
                                            :id => params[:fileobject][:cid],
                                            params: {
                                              :lid => params[:fileobject][:pid]
                                            }
                                          ),
              notice: 'File was successfully created.'}
            format.json { render :show, status: :created, location: @fileobject }
          elsif params[:fileobject][:type] == "material"
            format.html {
              redirect_to material_url(
                                       :id => params[:fileobject][:mid],
                                       params: {
                                         :cid => params[:fileobject][:cid],
                                         :pid => params[:fileobject][:pid]
                                         }
                                       ),
              notice: 'Fileobject was successfully destroyed.'
            }
            format.json { head :no_content, status: :created, location: @fileobject }
          end
        else
          format.html { render :new }
          format.json { render json: @fileobject.errors, status: :unprocessable_entity }
        end
      end
    
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @fileobject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fileobjects/1
  # PATCH/PUT /fileobjects/1.json
  def update
    respond_to do |format|
      if @fileobject.update(fileobject_params)
        format.html { redirect_to @fileobject, notice: 'Fileobject was successfully updated.' }
        format.json { render :show, status: :ok, location: @fileobject }
      else
        format.html { render :edit }
        format.json { render json: @fileobject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fileobjects/1
  # DELETE /fileobjects/1.json
  def destroy
    @fileobject.destroy
    respond_to do |format|
      if params[:type] == "consolidation"
        format.html { redirect_to consolidation_url(:id => params[:cid], params: {:lid => params[:pid]}),
          notice: 'Fileobject was successfully destroyed.'
        }
        format.json { head :no_content }
        
      elsif params[:type] == "material"
        format.html { redirect_to material_url(:id => params[:mid], params: {:cid => params[:cid], :pid => params[:pid]}),
          notice: 'Fileobject was successfully destroyed.'
        }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fileobject
      @fileobject = Fileobject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fileobject_params
      params.require(:fileobject).permit(
                                         :uuid,
                                         :consolidation,
                                         :material,
                                         :created_date,
                                         :modified_date,
                                         :file,
                                         :file_type,
                                         :alias_name,
                                         :status,
                                         :make_public,
                                         :is_locked,
                                         :source,
                                         :file_operation,
                                         :operating_application,
                                         :caption,
                                         :description,
                                         :flickr_photoid,
                                         :file_cache
                                        )
    end
end

server/app/helpers/fileobjects_helper.rb
module FileobjectsHelper
end

server/app/views/fileobjects/_form.html.erb
<%= form_with(model: fileobject, local: true) do |form| %>
  <% if fileobject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fileobject.errors.count, "error") %> prohibited this fileobject from being saved:</h2>

      <ul>
      <% fileobject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table>
    <tr>
      <td colspan="2">
        <div class="field" style="text-align: center">
          <% logger.debug("Path #{@fileobject.file.url}") %>
          <% if @fileobject.file.url != nil %>
            <% if @fileobject.file_type == "Image" %>
                <%
                    img_width, img_height = FastImage.size(@fileobject.file.path)
                    if img_width >= img_height
                        shw_height = (img_height * 800) / img_width
                        shw_width = 800
                    else
                        shw_width = (img_width * 600) / img_height
                        shw_height = 600
                    end
                %>
                <%= image_tag(@fileobject.file.url, :height => shw_height, :width => shw_width) %>
            <% elsif @fileobject.file_type == "Sound" %>
                <audio id="player" controls>
                    <source src="<%= @fileobject.file.url %>">
                </audio>
            <% else %>
              <img src=<%= image_url('noimage.jpg') %> height="300px" /> 
            <% end %>
          <% end %>
          <br /><br />
          <%= form.file_field :file %>
          <%= form.hidden_field :file_cache %>
        </div>
      </td>
    </tr>
    <tr>
      <th style="width: 150px"><%= form.label :uuid %></th>
      <td style="width: 300px"><%= form.text_field :uuid, :class => "text_field", :readonly => true %></td>
    </tr>
    <tr><th><%= form.label :consolidation %></th><td style="width: 300px"><%= form.text_field :consolidation, :class => "text_field", :readonly => true %></td></tr>
    <tr><th><%= form.label :material %></th><td style="width: 300px"><%= form.text_field :material, :class => "text_field", :readonly => true %></td></tr>
    <tr><th><%= form.label :created_date %></th><td style="width: 300px"><%= form.date_select :created_date %></td></tr>
    <tr><th><%= form.label :modified_date %></th><td style="width: 300px"><%= form.date_select :modified_date %></td></tr>
    <tr><th><%= form.label :alias_name %></th><td style="width: 300px"><%= form.text_field :alias_name, :class => "text_field"%></td></tr>
    <tr><th><%= form.label :status %></th><td style="width: 300px"><%= form.text_field :status, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :make_public %></th><td style="width: 300px"><%= form.check_box :make_public, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :is_locked %></th><td style="width: 300px"><%= form.check_box :is_locked, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :source %></th><td style="width: 300px"><%= form.text_field :source, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :file_operation %></th><td style="width: 300px"><%= form.text_field :file_operation, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :operating_application %></th><td style="width: 300px"><%= form.text_field :operating_application, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :caption %></th><td style="width: 300px"><%= form.text_field :caption, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :description %></th><td style="width: 300px"><%= form.text_area :description, :class => "text_field" %></td></tr>
    <tr><th><%= form.label :flickr_photoid %></th><td style="width: 300px"><%= form.text_field :flickr_photoid, :class => "text_field" %></td></tr>
  </table>

  <div class="actions" style="text-align: right">
    <%= form.hidden_field :mid, :value => params[:mid] %>
    <%= form.hidden_field :cid, :value => params[:cid] %>
    <%= form.hidden_field :pid, :value => params[:pid] %>
    <%= form.hidden_field :type, :value => params[:type] %>
    <%= form.submit %>
  </div>
<% end %>

server/app/views/fileobjects/edit.html.erb
<h2>
    <img src=<%= image_url('icons/ic_description_black_48dp.png') %> />
    File: <%= @fileobject.uuid %>
</h2>
<hr />
<div class="btn-group">
    <% if params[:type] == "consolidation" %>
        <%=
         button_to consolidation_url(:id => params[:cid]),
         {
            method: :get, :class => "btn btn-secondary",
            :style => "width: 90px; border-radius: 0 !important;",
            params: {:lid => params[:pid]}
         } do %>
         <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
        <% end %>
        
        <%= button_to @fileobject,
            {
                method: :get, :class => "btn btn-primary",
                :style => "width: 90px; border-radius: 0 !important;",
                params: {
                    type: params[:type],
                    cid: params[:cid],
                    pid: params[:lid]
                }
            } do%>
            <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
        <% end %>
    <% elsif params[:type] == "material" %>
        <%=
         button_to material_url(:id => params[:mid]),
         {
            method: :get, :class => "btn btn-secondary",
            :style => "width: 90px; border-radius: 0 !important;",
            params: {
                :cid => params[:cid],
                :pid => params[:pid]
            }
         } do %>
         <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
        <% end %>
        
        <%= button_to @fileobject,
            {
                method: :get, :class => "btn btn-primary",
                :style => "width: 90px; border-radius: 0 !important;",
                params: {
                    type: params[:type],
                    mid: params[:mid],
                    cid: params[:cid],
                    pid: params[:pid]
                }
            } do%>
            <img src=<%= image_url('icons/ic_visibility_white_18dp.png') %>/>
        <% end %>
    <% end %>
</div>
<hr />

<%= render 'form', fileobject: @fileobject %>


    

server/app/views/fileobjects/index.html.erb
<h1>Files</h1>
<hr />
<%= button_to 'New File', new_fileobject_path, {method: :get, :class => "btn btn-success", :style => "width: 150px; border-radius: 0 !important;"} %>
<hr />

<table>
  <thead>
    <tr>
      <th style="width: 100px">Modified</th>
      <th style="width: 200px">Name</th>
      <th style="width: 200px">Alias</th>
      <th style="width: 200px">Type</th>
      <th style="width: 200px">Status</th>
      <th style="width: 100px">Public</th>
      <th style="width: auto"></th>
    </tr>
  </thead>

  <tbody>
    <% @fileobjects.each do |fileobject| %>
      <tr class="zebra">
        <td><%= fileobject.modified_date %></td>
        <td><%= fileobject.file %></td>
        <td><%= fileobject.alias_name %></td>
        <td><%= fileobject.file_type %></td>
        <td><%= fileobject.status %></td>
        <td><%= fileobject.make_public %></td>
        <td><div class="btn-group">
          <%= button_to 'Show', fileobject, {method: :get, :class => "btn btn-primary", :style => "width: 90px; border-radius: 0 !important;"} %>
          <%= button_to 'Edit', edit_fileobject_path(fileobject), {method: :get, :class => "btn btn-warning", :style => "width: 90px; border-radius: 0 !important;"} %>
          <%= button_to 'Delete', fileobject, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "width: 90px; border-radius: 0 !important;" %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

server/app/views/fileobjects/new.html.erb
<h2>
  <img src=<%= image_url('icons/ic_inbox_black_48dp.png') %> />
  New File
</h2>
<hr />
<div class="btn-group">
  <% if params[:type] == "consolidation" %>
    <%=
      button_to consolidation_url(:id => params[:cid]),
      {
        method: :get, :class => "btn btn-secondary",
        :style => "width: 90px; border-radius: 0 !important;",
        params: {:lid => params[:pid]}
      } do %>
          <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
    <% end %>
  <% elsif params[:type] == "material" %>
    <%=
      button_to material_url(:id => params[:mid]),
      {
        method: :get, :class => "btn btn-secondary",
        :style => "width: 90px; border-radius: 0 !important;",
        params: {:cid => params[:cid], :lid => params[:pid]}
      } do %>
          <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
    <% end %>
  <% end %>
</div>
<hr />

<%= render 'form', fileobject: @fileobject %>



  

server/app/views/fileobjects/show.html.erb
<h2>
 <img src=<%= image_url('icons/ic_description_black_48dp.png') %> />
 File: <%= @fileobject.uuid %>
</h2>
<hr />
<div class="btn-group">
    <% if params[:type] == "consolidation" %>
        <%=
            button_to consolidation_url(:id => params[:cid]),
            {
               method: :get, :class => "btn btn-secondary",
               :style => "width: 90px; border-radius: 0 !important;",
               params: {
                   :lid => params[:pid]
               }
            } do %>
            <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
           <% end %>
           <%=
            button_to edit_fileobject_path(@fileobject),
            {
               method: :get, :class => "btn btn-warning",
               :style => "width: 90px; border-radius: 0 !important;",
               params: {
                  type: params[:type],
                  cid: params[:cid],
                  pid: params[:pid]
               }
            } do %>
            <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
        <% end %>
    <% elsif params[:type] == "material" %>
        <%=
            button_to material_url(:id => params[:mid]),
            {
               method: :get, :class => "btn btn-secondary",
               :style => "width: 90px; border-radius: 0 !important;",
               params: {
                   :cid => params[:cid],
                   :pid => params[:pid]
               }
            } do %>
            <img src=<%= image_url('icons/ic_reply_white_18dp.png') %>/>
           <% end %>
           <%=
            button_to edit_fileobject_path(@fileobject),
            {
               method: :get, :class => "btn btn-warning",
               :style => "width: 90px; border-radius: 0 !important;",
               params: {
                  type: params[:type],
                  mid: params[:mid],
                  cid: params[:cid],
                  pid: params[:pid]
               }
            } do %>
            <img src=<%= image_url('icons/ic_create_white_18dp.png') %>/>
        <% end %>
    <% end %>
</div>
<hr />

<div class="row">
    <div class="col-sm-6" style="text-align: center; vertical-align: middle">
        <% if @fileobject.file_type == "Image" %>
            <%
                img_width, img_height = FastImage.size(@fileobject.file.path)
                if img_width >= img_height
                    shw_height = (img_height * 550) / img_width
                    shw_width = 550
                else
                    shw_width = (img_width * 350) / img_height
                    shw_height = 350
                end
            %>
            <%= image_tag(@fileobject.file.url, :height => shw_height, :width => shw_width) %>
        <% elsif @fileobject.file_type == "Sound" %>
            <img src=<%= image_url('noimage.jpg') %> height="300px" />
            <audio id="player" controls>
                <source src="<%= @fileobject.file.url %>">
            </audio>
        <% end %>
    </div>
    
    <div class="col-sm-6">
        <p><strong>Uuid:</strong><%= @fileobject.uuid %></p>
        <p><strong>Consolidation:</strong><%= @fileobject.consolidation %></p>
        <p><strong>Material:</strong><%= @fileobject.material %></p>
        <p><strong>Created date:</strong><%= @fileobject.created_date %></p>
        <p><strong>Modified date:</strong><%= @fileobject.modified_date %></p>
        <p><strong>File name:</strong><%= @fileobject.file %></p>
        <p><strong>File type:</strong><%= @fileobject.file_type %></p>
        <p><strong>Alias name:</strong><%= @fileobject.alias_name %></p>
        <p><strong>Status:</strong><%= @fileobject.status %></p>
        <p><strong>Make public:</strong><%= @fileobject.make_public %></p>
        <p><strong>Is locked:</strong><%= @fileobject.is_locked %></p>
        <p><strong>Source:</strong><%= @fileobject.source %></p>
        <p><strong>File operation:</strong><%= @fileobject.file_operation %></p>
        <p><strong>Operating application:</strong><%= @fileobject.operating_application %></p>
        <p><strong>Caption:</strong><%= @fileobject.caption %></p>
        <p><strong>Description:</strong><%= @fileobject.description %></p>
        <p><strong>Flickr photoid:</strong><%= @fileobject.flickr_photoid %></p>
    </div>
</div>